### ISSUE TITLE
Ender tank not working as a chunck loader

### ISSUE THREAD

**Issue by AbrahamArmasCordero** [TheCBProject/EnderStorage#109]
I have Two tanks in a Lan Server, one in the overworld and the other in the nether with a buildcraft pump with three redstone engines and vanilla redstone setup to switch engines On and Off

Im playing with my roommate and when we are both in the overworld lava doesn' t get teleported
to overworld, im guessing its chunck loading related or BC alpha version doing something weird

BC version: 7.99.23 (because 7.99.24.1 makes a crash nvm) 
Ender storage version: 2.4.5.135
MC version: 1.12.2

Ideas to fix it: 

1. Just install your chunck loader mod see if that works
2. Upgrade BC version to see if thats solves it
3. Reset server to see if that fixes it

**Comment by Ecu** [comment]
Unless something has changed since I last really looked at the code, Ender Storage doesn't chunk load.  It doesn't teleport resources from point A to point B.  Instead, every color code represents an inventory/tank and the block just accesses that when loaded.  

You would still need a chunk loader if you want the chunk to load to allow the resources to be used at the other end.
