### ISSUE TITLE
Fatal crash after booting to title screen 

### ISSUE THREAD

**Issue by arranreedman** [TheCBProject/EnderStorage#11]
About a second after booting to the title screen, the game crashes (crash log is linked below)
My theory is that another mod, 'menu mobs' causes a conflict with EnderStorage as on removing 'menu mobs' the problem does not occur

http://pastebin.com/LCa211nG

**Comment by covers1624** [comment]
They must be doing some weird things to events, I'll look in to it later on today when I'm at my computer.

**Comment by arranreedman** [comment]
Yeah, that was my guess... I just thought it would be best to let you know to avoid future issues e.t.c. glad I could help

**Comment by Morpheus1101** [comment]
Im getting this crash as well Log @ http://pastebin.com/N7Psu8Em very very minor diff between my crash report and the other .. but deff the same issue

**Comment by arranreedman** [comment]
I don't know much about modding, I am just a user, so I have no idea what is causing your problem. It's not the end of the world for me because i didn't really need that other mod; i just wanted to let you guys know that there is an issue afoot!

**Comment by covers1624** [comment]
Can i have a link to this mod causing the crash, the only way this could happen is if the world load event is not fired on the client..

**Comment by arranreedman** [comment]
https://minecraft.curseforge.com/projects/menumobs
This is the one that I think caused it

**Comment by Morpheus1101** [comment]
I have this mod in my pack, have disabled it and testing now.... Ok after disabling the mod, i can confirm that menmobs is indeed the issue

**Comment by arranreedman** [comment]
The difference with the error that I came across and the one that the report it linked to is that the title screen had only just loaded when it crashed; I hadn't got around to making a world which is where the other error apears to have occured...

**Comment by arranreedman** [comment]
But yes, I thought that menumobs was the issue... out of interest, do you think it is something you can fix on your end or should I send the same bug report to the other mod's creator?

**Comment by covers1624** [comment]
I would hold of on reporting it to him as Morph has already done that, tomorrow ill investigate why this is happening in more depth and see if i can fix it for the other mod.

**Comment by arranreedman** [comment]
Sounds good... glad I could help

**Comment by bschoenmaeckers** [comment]
I'm defining mc.thePlayer to load a fake nonticking world. EnderStorage crashes at [clientState.update()](https://github.com/TheCBProject/EnderStorage/blob/df858a0930034c5594d3ff706136beb8883f7270/src/main/java/codechicken/enderstorage/network/TankSynchroniser.java#L265) because onWorldLoad never has been called. The null check above it checks if [mc().getConnection() != null](https://github.com/TheCBProject/CodeChickenLib/blob/463cf6b04728cb4fb779a7a84f69fa25517eefff/src/main/java/codechicken/lib/util/ClientUtils.java#L22) wich will return true because mc.thePlayer.connection isn't null.
I propose to check in [ClientUtils.inWorld()](https://github.com/TheCBProject/CodeChickenLib/blob/463cf6b04728cb4fb779a7a84f69fa25517eefff/src/main/java/codechicken/lib/util/ClientUtils.java#L21-L23) if mc().theworld != null instead of the connection if this wasn't done on purpose.

**Comment by Morpheus1101** [comment]
This has now been fixed

**Comment by bschoenmaeckers** [comment]
This hasn't been fixed right?

**Comment by covers1624** [comment]
I was going off what Morph said.

**Comment by covers1624** [comment]
So is this fixed now?

**Comment by bschoenmaeckers** [comment]
Yes it is fixed.
