### ISSUE TITLE
[Feature Request] Disable fancy animation when chest closed

### ISSUE THREAD

**Issue by Krutoy242** [TheCBProject/EnderStorage#216]
I found, that even if Chest is closed, MC still renders its Ender Portal

![image](https://user-images.githubusercontent.com/936618/236614497-fd0d9d4b-fc5f-4889-9e13-893178f2410a.png)

This caused slightly FPS lag. It can be seen on Spark profiler

![image](https://user-images.githubusercontent.com/936618/236614563-ce57e82b-3afd-4152-bfb1-4f358639105b.png)

Please skip drawing portal if chest not opened 😀
Or add config option to disable this "space" render at all.

**Comment by covers1624** [comment]
'Causing slignt fps lag' is very much an overstatement.

However, the Ender Chest has done this since 1.15.x: https://github.com/TheCBProject/EnderStorage/blob/1.15.x/src/main/java/codechicken/enderstorage/client/render/tile/RenderTileEnderChest.java#L55

In the future, please provide more in-depth information about which mod version and Minecraft version you are reporting the issue for.

**Comment by Krutoy242** [comment]
Please provide issue template, so issue makers will know what information is appreciated.
