### ISSUE TITLE
[Feature Request] Command to clear EnderStorage inventories

### ISSUE THREAD

**Issue by Mohron** [TheCBProject/EnderStorage#27]
I would like to request a command to easily clear all Ender Chests/Tanks, global or for a specified player. I would like to be as thorough as possible when reseting a player's island on my skyblock servers but there's currently no easy way to clear this mods personal end-based inventories like you can a vanilla inventory and enderchest.

Example Usage: `/clearenderstorage [player]`

Thank you for your consideration!

**Comment by Ecu** [comment]
Unless something has changed, Ender Storage inventory should be stored in a unique location (been awhile since I've personally looked into the source), so you should be able to wipe said file and clear their stuff.

That said, I don't really see a problem for an administrator level command being implemented to do what you ask.  @covers1624, I'll leave this up to you.

**Comment by covers1624** [comment]
Yep, All ES data is inside the world folder, sadly, deleting the file will delete all ES data, so a command will work for this.

**Comment by covers1624** [comment]
This has been implemented! \o/ Grab the latest CCL and ES from CB's site and check it out. Let me know of any way to improve the commands, i kinda made it very simple and there is a lot of in game help regarding how to use the commands. Once i know it doesn't have any immediate issues ill push it to curse, i have tested on a dedicated server and single player and all seems well.
