### ISSUE TITLE
1.10.2 update planned?

### ISSUE THREAD

**Issue by LordHellscream** [TheCBProject/EnderStorage#3]
Is there a plan to update this mod to 1.10.2? thanks :)

**Comment by covers1624** [comment]
Currently the latest build of Ender Storage over here:
 http://chickenbones.net/Pages/links.html will load on 1.10, Official
1.10 will be released as soon as i am sure there is no game breaking
bugs in the 1.9.4 version as that is what BTM is running. So hopefully
in the next day or so. Can you close this please as i cant over email.

----- Original Message -----
From: "TheCBProject/EnderStorage" 
To:"TheCBProject/EnderStorage" 
Cc:
Sent:Tue, 26 Jul 2016 22:29:35 -0700
Subject:[TheCBProject/EnderStorage] 1.10.2 update planned? (#3)

```
Is there a plan to update this mod to 1.10.2? thanks :)  

—
```

You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [1], or mute the
thread [2].     

## Links:

[1] https://github.com/TheCBProject/EnderStorage/issues/3
[2]

**Comment by LordHellscream** [comment]
closing as suggested

**Comment by covers1624** [comment]
Thanks. 

----- Original Message -----
