### ISSUE TITLE
[1.12.2] [Suggestion] Ender Buckets

### ISSUE THREAD

**Issue by Draskh** [TheCBProject/EnderStorage#62]
I would like to suggest to add Ender Buckets. It is the equivalent to Ender Pouch. It would be very useful to access to a tank if need a lots of liquid and you need just a one bucket because everything is stored in the Ender Tank.

**Comment by covers1624** [comment]
@Ecu Thoughts?

**Comment by Ecu** [comment]
Honestly, I don't really like the idea of an Ender Bucket.  I feel like it would just be rather clunky to manipulate.  I also already feel like the Ender Pouch is rather redundant and just kind of cheesy, as such I'm kind of loath to add another such item.

It really boils down to being something rather clunky though.  Buckets are already an interactive to get and place liquid.  Now you would need to be able to only get or only put in order to have the effective functionality of the tanks.  This would lead to creating modifier-based functionality (like shift) and I just don't see that as a clean implementation.

Edit - I had thought of a way to do it, but I changed my mind.  Honestly, I feel like the pouches should be taken out of the game.  The chests and tanks already can be accessed by placing them down and then picking them back up when you're done.  Ender Storage is already a crazily powerful mod, it doesn't need to be made even easier.

**Comment by Draskh** [comment]
I just thought like that: It was very useful if you need a big amount of some liquid. It can be pushed into the Ender Tank and easily be taken out with the Ender Bucket. 
I would not say it is "easier" with the Ender Bucket. It is just more comfortable 'cause you save several times of refilling the normal buckets.
But I never tought that is big effort to add that. I tought it is simple to access to the tank's inventory. 
But nevermind if you change your mind and add them you could implant a configuration to deactivate pouches and buckets.

**Comment by covers1624** [comment]
I guess its hard for me to justify the buckets as they can be spammed really easily and interact directly with the world, Either way its up to Ecu on this one, its his mod and what ever decision he comes to, is what will be done. Personally if puches were to be removed it would be via a config, and likewise with buckets if they were to be added, buckets likely to be disabled by default.

**Comment by Ecu** [comment]
It isn't so much a matter of a difficulty to code an Ender Bucket, but rather design how it is to be used.  

When you right click on a block of liquid, does the bucket take the liquid or does it place liquid from it's channel?  I cannot use shift to control this either, as it would ruin the ability to carefully go over an edge and either place or acquire liquids with said bucket.  A mode key would add additional hotkeys to an otherwise simple mod and complicate the process of using the tools.  Similarly speaking, adding two "buckets", one for get and one for place would also complicate the system.

All in all, if someone else wants to implement Ender Buckets as an addon or something, fine.  @covers1624, if you want to implement it as part of Ender Storage itself, it is your call as you are maintaining the mod.  However, my personal opinion is that if it cannot be done well, don't do it.

**Comment by covers1624** [comment]
Then its settled, ill add this to the list of things for an addon mod. This wont be appearing in ES.
