### ISSUE TITLE
World-Breaking bug, affects modded dimensions and possibly Overworld.

### ISSUE THREAD

**Issue by bossbasslol** [TheCBProject/EnderStorage#79]
I was playing in a survival game with this mod and Twilight Forest on, so far no problems.
      The real fun started when _I forgot to play with forge loaded_ and clicked "play" on my world; when I entered it the place was nothing but void. 
When I rejoined the same world with mods on, I was shocked to see the trees in the Twilight Forest dimension replaced with 1x1 stacks of **ENDERTANK** blocks. They where _all over_ the damn place and I almost passed out. 
       This made my world unplayable and I was forced to the delete the 120+ hours I put into it.
Please fix this strange bug.

**Comment by covers1624** [comment]
This isnt caused by Twilight Forest or EnderStorage, its caused by you loading your world without forge installed, this would have caused forge to reallocate id's when you joined back, nothing i can sorry. I can however recomend you stop using minecraft the way you have it setup, use multimc or something of the like so all your instances have seperate world / mods folders.
