### ISSUE TITLE
Suggestion - Power

### ISSUE THREAD

**Issue by generrosity** [TheCBProject/EnderStorage#90]
Dear, beloved, EnderStorage.

We have seen your chests and tanks and loved your mod, and made sure it has always been around and loved.  Its often quoted to being chunk-loading safe, nice on servers, and just a pleasure to use.

Can you extend into power?

We see a mod we hadn't seen before called Flux - https://minecraft.curseforge.com/projects/flux-networks - the interface is different, but its is Ender Storage of power. The in points, the out points, and the 'storage' are all independent items that hook into Ender space to transfer power. It has let us extend our chunk-safe server recommendations further.

Please please please, please, consider extend into the third form of resource of Power. I can only imagine it would be well received given the polish and reliability that you have shown with Liquids and Items.

If nothing else - thanks for your time, and thank you for years of Ender Storage 😜

**Comment by covers1624** [comment]
Since everything has moved to capabilities, Forge has a standard Energy capability now that is basically RF, but in Forge. I'm for this, but @Ecu is the deciding vote. Honestly, it'd mainly just be the model we need to sort out. It would also Not require any dependencies since the capability just exists in forge.

**Comment by Chicken-Bones** [comment]
I've declined this request numerous times in the past, due to three concerns, API, balance, thematic design.

Now that RF is in forge, concern 1 is no longer valid. 

I know several other mods have/had methods of wireless power transfer, each with their own rate limits and mechanics. Ender storage's approach to rate limiting has always been. "What?"

While Ender Storage is primarily used for transfer (especially with tanks) the implementations all store something. (Side note: I think Ender Buckets deserve a higher priority and I can't remember why they were never made). Ender RF storage, would need to function somewhat like an Energy Cell, in which case the question is "how much does it hold?". Ender Battery perhaps? Maybe 1M RF?

In any case, I've never had any artistic skill, so I'll leave such design decisions to my betters.

**Comment by generrosity** [comment]
A bucket that links to a tank like a pouch? Huh, nice!

Certainly more about the storage than the transfer.

I've always seen the number 16 associated with this mod; colours, tank bucket storage, ender pearl stack size.

Here is a reference to how much power a piece of coal generate, if useful https://www.reddit.com/r/feedthebeast/comments/4pak8h/i_compared_all_coal_generators/

16 to 36kRF seems to be the entry point... Making a stack of coal 1.024M RF?

It would indeed be a battery then. I do like the name "ender cell"?

Thanks again for considering this :)

**Comment by Ecu** [comment]
The main reason why I have been against a RF transfer mechanism in Ender Storage is that Ender Storage is meant to be a mod that works with Vanilla.  As Ender Storage itself has mo mechanisms for producing RF, and no mechanisms for using RF, it becomes rather pointless to have a mechanism to transfer RF.

There are a lot of concepts that could be made into 'Ender' devices that would even make more sense when compared to RF batteries.  For instance, we don't we have Ender Transmitters and Ender Receivers for redstone.

This all stated, I will defer to @covers1624 on this one.  If you feel that implementing it is worth having it as part of the mod itself, by all means, I approve.  To be completely honest, if I was in charge of the mod again...it would probably get a full balance overhaul as I am still not quite a fan of how easy it is to abuse currently.  I just don't really play Minecraft at all lately and have moved on to other things.

As for @Chicken-Bones mentioning Ender Buckets.  I believe this came up again in a prior suggestion.  The main reason I have been iffy on Ender Buckets is because I hadn't landed on a solid mechanism for use.  That said, I suppose we could just use left-click place liquid, right-click pick up liquid.  Linking it to a frequency would be handled the same way Ender Pouches are handled.

**Comment by covers1624** [comment]
This will not be happening sadly, i can't come up with a nice way of handling this and it just doesn't feel right imo.

**Comment by generrosity** [comment]
Much appreciate the consideration :) thanks!
