### ISSUE TITLE
[Suggestion] Autocrafting private Block and Copying Device

### ISSUE THREAD

**Issue by drunkripper** [TheCBProject/EnderStorage#98]
Maybe add a crafting recipe for private ender chests.
My idea is (Ender Storage Block) + a new crafting item that gets returned that tells the autocrafting system to use your name(You craft it, right click it and give it to AE2 or RS for autocrafting and it has an nbt of your Player/UUID) + a diamond.

Why? because when building mass ender chest setups clicking on each one just feels tedious and time consuming.

My other idea is make a copy tool, It copies the color combination and consumes dyes from your inventory to auto attach them (And apply the diamond if you have a diamond in your inventory).

**Comment by Ecu** [comment]
No.

**Comment by covers1624** [comment]
I've sunk a great deal of time contemplating a nice way to do this that still makes it somewhat secure from thieves, its not really possible. I have considered some sort of team lock in addition to the personal lock. Personally I would find that wayy more useful, since the people im basing with can then setup stuff when im not on line and vice versa, but i haven't really though of a neat way to do that either. So for the moment, no sorry this won't be happening.

**Comment by drunkripper** [comment]
@covers1624 Code wise idk how it would work similar to groups, but In game wise maybe similar to CoFH teams where teams are command based and using an emerald instead of a diamond for it (So it still would work in vanilla)?

**Comment by covers1624** [comment]
Code wise is easy, dw about that. Design wise though, Having a block explicitly for it seems kinda bleh, Vanilla's teams aren't really accessible to standard users, FTB's team system sounds nice, but that requires an external dependency, having a gui like CoFH is alright? i guess?, it still feels messy tbh. It requires some more thought. I want to add some form of group / team system for ChickenChunks, so people can share and edit loaders and such, but still not sure how to do that. Perhaps whacking people with sticks is the best option.. lol..
